version: "3.1"
services:

    mariadb:
      image: mariadb:10.1
      container_name: sql
      working_dir: /application
      volumes:
        - .:/application
        - ./mysql/data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=db
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
      networks:
       - www

    webserver:
      image: httpd:alpine
      container_name: webserver
      working_dir: /usr/local/apache2/htdocs/
      volumes:
          - ./html/:/usr/local/apache2/htdocs/
          - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      expose:
       - "80"
      environment:
       - VIRTUAL_HOST=webserver.ltd,www.webserver.ltd
      networks:
       - www

    php:
      build: php-fpm
      container_name: php-fpm
      hostname: php-fpm
      working_dir: /usr/local/apache2/htdocs/
      networks:
       - www
      volumes:
        - ./html/:/usr/local/apache2/htdocs/
        - ./php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini

networks:
  www:
    external:
      name: www