version: "3.1"
services:

    mariadb:
      restart: unless-stopped
      image: mariadb:10.1
      container_name: sql
      working_dir: /application
      volumes:
        - .:/application
        - ./mysql/data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=db
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
      networks:
       - private-network

    webserver:
      restart: unless-stopped
      image: httpd:alpine
      container_name: webserver
      working_dir: /usr/local/apache2/htdocs/
      volumes:
          - ./html/:/usr/local/apache2/htdocs/
          - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      expose:
       - "80"
      environment:
       - VIRTUAL_HOST=webserver.ltd,www.webserver.ltd
      networks:
       - www
       - private-network

    php:
      restart: unless-stopped
      image: php:7.2-fpm-alpine
      container_name: php-fpm
      hostname: php-fpm
      working_dir: /usr/local/apache2/htdocs/
      networks:
       - private-network
      volumes:
        - ./html/:/usr/local/apache2/htdocs/

networks:
  private-network:
    internal: true
  www:
    external:
      name: www